# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-29 17:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordem',
            name='data',
            field=models.DateField(blank=True, default=datetime.datetime(2017, 5, 29, 17, 7, 10, 973901)),
        ),
    ]
